### ISSUE TITLE
criar comandos usando apenas YAML

### ISSUE THREAD

**Issue by RodrigoDornelles** [aHub-Tech/twitch-hubble-bot#3]
conversando com @vcwild, pensamos em fazer um parser de YAML, onde salva os comandos como chaves e e os replies como membros no banco de cache redis, e é efetuado o comando quando chamado.

como pode ser a sintaxe:
```YAML
zapzap2: # comando principal
  aliases:  #alternativas para os comandos
  - zap2
  - whatsapp2
  replies: #alternativas de resposta
  - você conhece o zapzap2?
  - você quer o zapzap do emidio?
```
